package com.eventbooking.common.constant;

public enum ErrorCode {
  USER_NOT_FOUND,
  OUTLET_NOT_FOUND,
  BOOKING_NOT_FOUND,
  EVENT_NOT_FOUND,
  RESOURCE_NOT_FOUND,
  INVALID_CREDENTIALS,
  TOKEN_EXPIRED,
  UNAUTHORIZED,
  FORBIDDEN,
  CONFLICT,
  BAD_REQUEST,
  PAYMENT_FAILED,
  REVIEW_NOT_FOUND,
  NOTIFICATION_NOT_FOUND,
  MEMBERSHIP_NOT_FOUND,
  ADVERTISEMENT_NOT_FOUND,
  LOCATION_NOT_FOUND,
  INTERNAL_ERROR,
  EMAIL_ALREADY_EXISTS
}
